# Generated by Django 4.2.8 on 2023-12-29 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bedwars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(max_length=80, verbose_name='Контакт')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('team', models.CharField(max_length=24, verbose_name='Название команды')),
                ('player1', models.CharField(max_length=20, verbose_name='Участник №1')),
                ('player2', models.CharField(max_length=20, verbose_name='Участник №2')),
                ('player3', models.CharField(max_length=20, verbose_name='Участник №3')),
                ('player4', models.CharField(max_length=20, verbose_name='Участник №4')),
                ('working_status', models.BooleanField(default=False, verbose_name='В работе [СТАТУС]')),
                ('completed_status', models.BooleanField(default=False, verbose_name='Завершено [СТАТУС]')),
                ('approved_status', models.BooleanField(default=False, verbose_name='Одобрено [СТАТУС]')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата регистрации заявки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name_plural': 'Заявки [BEDWARS]',
            },
        ),
    ]
