# Generated by Django 4.0 on 2022-12-02 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='boost_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 21, 11, 4, 56908), verbose_name='Дата регистрации CloudBoost-статуса'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='premium_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 21, 11, 4, 56908), verbose_name='Дата регистрации премиум-статуса'),
        ),
    ]
