# Generated by Django 4.0 on 2022-12-03 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_servers_boost_regdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='boost_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 12, 50, 6, 279944), verbose_name='Дата регистрации CloudBoost-статуса'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='premium_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 12, 50, 6, 278947), verbose_name='Дата регистрации премиум-статуса'),
        ),
    ]
