# Generated by Django 4.0 on 2022-12-04 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_alter_servers_boost_regdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='boost_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 20, 16, 27, 548367), verbose_name='Дата регистрации CloudBoost-статуса'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='premium_regdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 20, 16, 27, 548367), verbose_name='Дата регистрации премиум-статуса'),
        ),
    ]
