# Generated by Django 4.2.8 on 2023-12-29 00:44

import datetime
from django.db import migrations, models
import servers.models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_alter_servers_boost_regdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=servers.models.rename_illustration)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Иллюстрации',
            },
        ),
        migrations.AddField(
            model_name='servers',
            name='illustrations_rate_add',
            field=models.BooleanField(default=False, verbose_name='Рейтинг за иллюстрации'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='boost_regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 19, 43, 50, 622109), verbose_name='Дата регистрации CloudBoost-статуса'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='premium_regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 19, 43, 50, 622109), verbose_name='Дата регистрации премиум-статуса'),
        ),
        migrations.AlterField(
            model_name='servers',
            name='version',
            field=models.CharField(choices=[('1.7', '1.7.X'), ('1.8', '1.8.X'), ('1.9', '1.9.X'), ('1.10', '1.10.X'), ('1.11', '1.11.X'), ('1.12', '1.12.X'), ('1.13', '1.13.X'), ('1.14', '1.14.X'), ('1.15', '1.15.X'), ('1.16', '1.16.X'), ('1.17', '1.17.X'), ('1.18', '1.18.X'), ('1.19', '1.19.X')], default='1.19', max_length=10, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='servers',
            name='illustrations',
            field=models.ManyToManyField(blank=True, null=True, to='servers.illustrations', verbose_name='Иллюстрации'),
        ),
    ]
